openapi: 3.1.0
info:
  title: Setup
  description: Needs a description.
paths:
  /setup/api/configcheck:
    get:
      summary: Get the configuration status
      description: >-
        This endpoint allows you to check the status of the most recent
        configuration process:


        Note that you may need to wait several seconds after you start a process
        before you can check its status.


        The different statuses are:


        | Status        | Description                       |

        | - |  |

        | `PENDING`     | The job has not started yet       |

        | `CONFIGURING` | The job is running                |

        | `DONE`        | The job has finished correctly    |

        | `FAILED`      | The job has finished unexpectedly |
      operationId: enterprise-admin/get-configuration-status
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-the-configuration-status
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configuration-status'
              examples:
                default:
                  $ref: '#/components/examples/configuration-status'
        '401':
          description: Unauthorized
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/configure:
    post:
      summary: Start a configuration process
      description: >-
        This endpoint allows you to start a configuration process at any time
        for your updated settings to take effect:
      operationId: enterprise-admin/start-configuration-process
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#start-a-configuration-process
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '202':
          description: Response
        '401':
          description: Unauthorized
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/maintenance:
    get:
      summary: Get the maintenance status
      description: 'Check your installation''s maintenance status:'
      operationId: enterprise-admin/get-maintenance-status
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-the-maintenance-status
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/maintenance-status'
              examples:
                default:
                  $ref: '#/components/examples/maintenance-status'
        '401':
          description: Unauthorized
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
    post:
      summary: Enable or disable maintenance mode
      description: >-
        **Note:** The request body for this operation must be submitted as
        `application/x-www-form-urlencoded` data. You can submit a parameter
        value as a string, or you can use a tool such as `curl` to submit a
        parameter value as the contents of a text file. For more information,
        see the [`curl`
        documentation](https://curl.se/docs/manpage.html#--data-urlencode).
      operationId: enterprise-admin/enable-or-disable-maintenance-mode
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#enable-or-disable-maintenance-mode
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/maintenance-status'
              examples:
                default:
                  $ref: '#/components/examples/maintenance-status'
        '401':
          description: Unauthorized
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                maintenance:
                  type: string
                  description: >-
                    A JSON string with the attributes `enabled` and `when`.


                    The possible values for `enabled` are `true` and `false`.
                    When it's `false`, the attribute `when` is ignored and the
                    maintenance mode is turned off. `when` defines the time
                    period when the maintenance was enabled.


                    The possible values for `when` are `now` or any date
                    parseable by
                    [mojombo/chronic](https://github.com/mojombo/chronic).
              required:
                - maintenance
            examples:
              default:
                value:
                  maintenance: '{"enabled":true, "when":"now"}'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/settings:
    get:
      summary: Get settings
      description: >-
        Gets the settings for your instance. To change settings, see the [Set
        settings
        endpoint](https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#set-settings).


        **Note:** You cannot retrieve the management console password with the
        Enterprise administration API.
      operationId: enterprise-admin/get-settings
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-settings
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enterprise-settings'
              examples:
                default:
                  $ref: '#/components/examples/enterprise-settings'
        '401':
          description: Unauthorized
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
    put:
      summary: Set settings
      description: >-
        Applies settings on your instance. For a list of the available settings,
        see the [Get settings
        endpoint](https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-settings).


        **Notes:**


        - The request body for this operation must be submitted as
        `application/x-www-form-urlencoded` data. You can submit a parameter
        value as a string, or you can use a tool such as `curl` to submit a
        parameter value as the contents of a text file. For more information,
        see the [`curl`
        documentation](https://curl.se/docs/manpage.html#--data-urlencode).

        - You cannot set the management console password with the Enterprise
        administration API. Use the `ghe-set-password` utility to change the
        management console password. For more information, see "[Command-line
        utilities](https://docs.github.com/enterprise-server@3.9/admin/configuration/configuring-your-enterprise/command-line-utilities#ghe-set-password)."
      operationId: enterprise-admin/set-settings
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#set-settings
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '204':
          description: Response
        '401':
          description: Unauthorized
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                settings:
                  type: string
                  description: >-
                    A JSON string with the new settings. Note that you only need
                    to pass the specific settings you want to modify. For a list
                    of the available settings, see the [Get settings
                    endpoint](https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-settings).
              required:
                - settings
            examples:
              '204':
                value:
                  settings: '{ "enterprise": { "public_pages": true }}'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/settings/authorized-keys:
    get:
      summary: Get all authorized SSH keys
      description: ''
      operationId: enterprise-admin/get-all-authorized-ssh-keys
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-all-authorized-ssh-keys
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ssh-key'
              examples:
                default:
                  $ref: '#/components/examples/ssh-key-items'
        '401':
          description: Unauthorized
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
    post:
      summary: Add an authorized SSH key
      description: >-
        **Note:** The request body for this operation must be submitted as
        `application/x-www-form-urlencoded` data. You can submit a parameter
        value as a string, or you can use a tool such as `curl` to submit a
        parameter value as the contents of a text file. For more information,
        see the [`curl`
        documentation](https://curl.se/docs/manpage.html#--data-urlencode).
      operationId: enterprise-admin/add-authorized-ssh-key
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#add-an-authorized-ssh-key
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ssh-key'
              examples:
                default:
                  $ref: '#/components/examples/ssh-key-items'
        '401':
          description: Unauthorized
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                authorized_key:
                  type: string
                  description: The public SSH key.
              required:
                - authorized_key
            examples:
              default:
                value:
                  authorized_key: >-
                    ssh-rsa
                    AAAAB3NzaC1yc2EAAAADAQABAAAAgQCssTL/Vtu/ODLTj0VtZoRAbvf7uiv5997GyDq0MoAZUjb5jmA5wYe2/wF6sFuhiZTnZoF1ZtCHunPp0hM/GHrn6VySBhNncx14YO8FPt1CIhEeRMSEjUK9cY3xAbS365oXY8vnUHJsS9+1tr/2bx/+4NJfcUt/Ezf1OR/0LStQXw==
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
    delete:
      summary: Remove an authorized SSH key
      description: >-
        **Note:** The request body for this operation must be submitted as
        `application/x-www-form-urlencoded` data. You can submit a parameter
        value as a string, or you can use a tool such as `curl` to submit a
        parameter value as the contents of a text file. For more information,
        see the [`curl`
        documentation](https://curl.se/docs/manpage.html#--data-urlencode).
      operationId: enterprise-admin/remove-authorized-ssh-key
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#remove-an-authorized-ssh-key
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ssh-key'
              examples:
                default:
                  $ref: '#/components/examples/ssh-key-items'
        '401':
          description: Unauthorized
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                authorized_key:
                  type: string
                  description: The public SSH key.
              required:
                - authorized_key
            examples:
              default:
                value:
                  authorized_key: >-
                    ssh-rsa
                    AAAAB3NzaC1yc2EAAAADAQABAAAAgQCssTL/Vtu/ODLTj0VtZoRAbvf7uiv5997GyDq0MoAZUjb5jmA5wYe2/wF6sFuhiZTnZoF1ZtCHunPp0hM/GHrn6VySBhNncx14YO8FPt1CIhEeRMSEjUK9cY3xAbS365oXY8vnUHJsS9+1tr/2bx/+4NJfcUt/Ezf1OR/0LStQXw==
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/start:
    post:
      summary: Create a GitHub license
      description: >-
        When you boot a GitHub instance for the first time, you can use the
        following endpoint to upload a license.


        Note that you need to `POST` to
        [`/setup/api/configure`](https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#start-a-configuration-process)
        to start the actual configuration process.


        When using this endpoint, your GitHub instance must have a password set.
        This can be accomplished two ways:


        1.  If you're working directly with the API before accessing the web
        interface, you must pass in the password parameter to set your password.

        2.  If you set up your instance via the web interface before accessing
        the API, your calls to this endpoint do not need the password parameter.


        **Note:** The request body for this operation must be submitted as
        `multipart/form-data` data. You can can reference the license file by
        prefixing the filename with the `@` symbol using `curl`. For more
        information, see the [`curl`
        documentation](https://curl.se/docs/manpage.html#-F).
      operationId: enterprise-admin/create-enterprise-server-license
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#create-a-github-license
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '202':
          description: Response
        '401':
          description: Unauthorized
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                license:
                  type: string
                  description: The content of your _.ghl_ license file.
                password:
                  type: string
                  description: >-
                    You **must** provide a password _only if_ you are uploading
                    your license for the first time. If you previously set a
                    password through the web interface, you don't need this
                    parameter.
                settings:
                  type: string
                  description: >-
                    An optional JSON string containing the installation
                    settings. For a list of the available settings, see the [Get
                    settings
                    endpoint](https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#get-settings).
              required:
                - license
            examples:
              default:
                value:
                  license: '@enterprise.ghl'
                  password: secret
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
  /setup/api/upgrade:
    post:
      summary: Upgrade a license
      description: >-
        This API upgrades your license and also triggers the configuration
        process.


        **Note:** The request body for this operation must be submitted as
        `multipart/form-data` data. You can can reference the license file by
        prefixing the filename with the `@` symbol using `curl`. For more
        information, see the [`curl`
        documentation](https://curl.se/docs/manpage.html#-F).
      operationId: enterprise-admin/upgrade-license
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/management-console#upgrade-a-license
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      responses:
        '202':
          description: Response
        '401':
          description: Unauthorized
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                license:
                  type: string
                  description: The content of your new _.ghl_ license file.
            examples:
              default:
                value:
                  license: '@enterprise.ghl'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: management-console
components:
  schemas:
    configuration-status:
      type: object
      properties:
        status:
          type: string
        progress:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              key:
                type: string
            required:
              - status
              - key
    maintenance-status:
      type: object
      properties:
        status:
          type: string
        scheduled_time:
          type: string
        connection_services:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              number:
                type: integer
            required:
              - name
              - number
    enterprise-settings:
      type: object
      properties:
        enterprise:
          type: object
          properties:
            private_mode:
              type: boolean
            public_pages:
              type: boolean
            subdomain_isolation:
              type: boolean
            signup_enabled:
              type: boolean
            github_hostname:
              type: string
            identicons_host:
              type: string
            http_proxy:
              nullable: true
              type: string
            auth_mode:
              type: string
            expire_sessions:
              type: boolean
            admin_password:
              nullable: true
              type: string
            configuration_id:
              type: integer
            configuration_run_count:
              type: integer
            avatar:
              type: object
              properties:
                enabled:
                  type: boolean
                uri:
                  type: string
            customer:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                uuid:
                  type: string
                secret_key_data:
                  type: string
                public_key_data:
                  type: string
            license:
              type: object
              properties:
                seats:
                  type: integer
                evaluation:
                  type: boolean
                perpetual:
                  type: boolean
                unlimited_seating:
                  type: boolean
                support_key:
                  type: string
                ssh_allowed:
                  type: boolean
                cluster_support:
                  type: boolean
                expire_at:
                  type: string
            github_ssl:
              type: object
              properties:
                enabled:
                  type: boolean
                cert:
                  nullable: true
                  type: string
                key:
                  nullable: true
                  type: string
            ldap:
              type: object
              properties:
                host:
                  nullable: true
                  type: string
                port:
                  type: integer
                base:
                  type: array
                  items: {}
                uid:
                  nullable: true
                  type: string
                bind_dn:
                  nullable: true
                  type: string
                password:
                  nullable: true
                  type: string
                method:
                  type: string
                search_strategy:
                  type: string
                user_groups:
                  type: array
                  items: {}
                admin_group:
                  nullable: true
                  type: string
                virtual_attribute_enabled:
                  type: boolean
                recursive_group_search:
                  type: boolean
                posix_support:
                  type: boolean
                user_sync_emails:
                  type: boolean
                user_sync_keys:
                  type: boolean
                user_sync_interval:
                  type: integer
                team_sync_interval:
                  type: integer
                sync_enabled:
                  type: boolean
                reconciliation:
                  type: object
                  properties:
                    user:
                      nullable: true
                      type: string
                    org:
                      nullable: true
                      type: string
                profile:
                  type: object
                  properties:
                    uid:
                      type: string
                    name:
                      nullable: true
                      type: string
                    mail:
                      nullable: true
                      type: string
                    key:
                      nullable: true
                      type: string
            cas:
              type: object
              properties:
                url:
                  nullable: true
                  type: string
            saml:
              type: object
              properties:
                sso_url:
                  nullable: true
                  type: string
                certificate:
                  nullable: true
                  type: string
                certificate_path:
                  nullable: true
                  type: string
                issuer:
                  nullable: true
                  type: string
                idp_initiated_sso:
                  type: boolean
                disable_admin_demote:
                  type: boolean
            github_oauth:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                organization_name:
                  type: string
                organization_team:
                  type: string
            smtp:
              type: object
              properties:
                enabled:
                  type: boolean
                address:
                  type: string
                authentication:
                  type: string
                port:
                  type: string
                domain:
                  type: string
                username:
                  type: string
                user_name:
                  type: string
                enable_starttls_auto:
                  type: boolean
                password:
                  type: string
                discard-to-noreply-address:
                  type: boolean
                support_address:
                  type: string
                support_address_type:
                  type: string
                noreply_address:
                  type: string
            ntp:
              type: object
              properties:
                primary_server:
                  type: string
                secondary_server:
                  type: string
            timezone:
              nullable: true
              type: string
            snmp:
              type: object
              properties:
                enabled:
                  type: boolean
                community:
                  type: string
            syslog:
              type: object
              properties:
                enabled:
                  type: boolean
                server:
                  nullable: true
                  type: string
                protocol_name:
                  type: string
            assets:
              nullable: true
              type: string
            pages:
              type: object
              properties:
                enabled:
                  type: boolean
            collectd:
              type: object
              properties:
                enabled:
                  type: boolean
                server:
                  nullable: true
                  type: string
                port:
                  type: integer
                encryption:
                  nullable: true
                  type: string
                username:
                  nullable: true
                  type: string
                password:
                  nullable: true
                  type: string
            mapping:
              type: object
              properties:
                enabled:
                  type: boolean
                tileserver:
                  nullable: true
                  type: string
                basemap:
                  type: string
                token:
                  nullable: true
                  type: string
            load_balancer:
              nullable: true
              type: string
        run_list:
          type: array
          items:
            type: string
